# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Kill Old Server
        run: |
          kill $(ps aux | grep 'sudo java -jar Server-1.0-jar-with-dependencies.jar&' | awk '{print $2}')
        continue-on-error: true

      
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: action-maven
        uses: comchangs/action-maven@v0.4-beta

      # Runs a single command using the runners shell
      - name: Build
        run: |
          cd Back-End
          mvn package
          cd target
          nohup sudo java -jar Server-1.0-jar-with-dependencies.jar &

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
